apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-api-postgres
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: salesflow-api
  delay:
    latency: "5000ms"
    correlation: "100"
    jitter: "0ms"
  direction: to
  target:
    selector:
      namespaces:
        - default
      labelSelectors:
        app: salesflow-postgres
    mode: all
  duration: "1h"
